"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabListButton = exports.TabListItem = exports.TabList = void 0;
var styled_components_1 = __importDefault(require("styled-components"));
exports.TabList = styled_components_1.default.ul(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  list-style: none;\n  display: inline-flex;\n  justify-content: center;\n  overflow: hidden;\n  overflow-x: auto;\n  max-width: 100%;\n  overflow-scrolling: touch;\n  overscroll-behavior-y: contain;\n  padding-bottom: 5px;\n  @media only screen and (max-width: ", ") {\n    justify-content: flex-start;\n  }\n  &::-webkit-scrollbar{\n    width: 5px;\n    height: 2px;\n    background-color: ", ";\n  }\n  &::-webkit-scrollbar-track{\n    border: none;\n    background-color: ", ";\n    border-radius: 1px;\n  }\n  &::-webkit-scrollbar-thumb{\n    background-color: ", ";\n    border-radius: 1px;\n  }\n"], ["\n  list-style: none;\n  display: inline-flex;\n  justify-content: center;\n  overflow: hidden;\n  overflow-x: auto;\n  max-width: 100%;\n  overflow-scrolling: touch;\n  overscroll-behavior-y: contain;\n  padding-bottom: 5px;\n  @media only screen and (max-width: ", ") {\n    justify-content: flex-start;\n  }\n  &::-webkit-scrollbar{\n    width: 5px;\n    height: 2px;\n    background-color: ", ";\n  }\n  &::-webkit-scrollbar-track{\n    border: none;\n    background-color: ", ";\n    border-radius: 1px;\n  }\n  &::-webkit-scrollbar-thumb{\n    background-color: ", ";\n    border-radius: 1px;\n  }\n"])), function (props) { var _a, _b, _c; return (_c = (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.breakpoint) === null || _b === void 0 ? void 0 : _b.small) === null || _c === void 0 ? void 0 : _c.max; }, function (props) { var _a, _b; return (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.color) === null || _b === void 0 ? void 0 : _b.white; }, function (props) { var _a, _b; return (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.color) === null || _b === void 0 ? void 0 : _b.graylight; }, function (props) { var _a, _b; return (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.color) === null || _b === void 0 ? void 0 : _b.gray; });
exports.TabListItem = styled_components_1.default.li(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  border-bottom: 1px solid ", ";\n"], ["\n  border-bottom: 1px solid ", ";\n"])), function (props) { var _a, _b; return (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.color) === null || _b === void 0 ? void 0 : _b.gray; });
exports.TabListButton = styled_components_1.default.button(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  color: ", ";\n  background: none;\n  border: none;\n  border-bottom: 2px solid ", ";\n  padding: 0.6rem 1.2rem;\n  transition: all .1s linear;\n  white-space: nowrap;\n\n  &:hover{\n    color: ", "\n  }\n"], ["\n  color: ", ";\n  background: none;\n  border: none;\n  border-bottom: 2px solid ", ";\n  padding: 0.6rem 1.2rem;\n  transition: all .1s linear;\n  white-space: nowrap;\n\n  &:hover{\n    color: ", "\n  }\n"])), function (props) { var _a, _b; return props.active ? (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.color) === null || _b === void 0 ? void 0 : _b.primary : 'inherit'; }, function (props) { return props.active ? 'currentColor' : 'transparent'; }, function (props) { var _a, _b; return (_b = (_a = props === null || props === void 0 ? void 0 : props.theme) === null || _a === void 0 ? void 0 : _a.color) === null || _b === void 0 ? void 0 : _b.primary; });
var templateObject_1, templateObject_2, templateObject_3;
